server:
  port: 9091

github:
  issues-detail-url: https://api.github.com/repos/kenshoo/python-style-guide/issues?rename=pr_key:pull_request.url,reported_by:user.login,developer:assignee.login,release:milestone.title&select=-ends_with(%22url%22),-starts_with(%22user%22),-starts_with(%22assignee%22),-starts_with(%22milestone%22),-title&mutate=created_at:ymd_hms(created_at),closed_at:ymd_hms(closed_at)&filter=state:closed,!is.na(pr_key)&mutate=age:as.numeric(closed_at%20-%20created_at,%20units%20=%20%22days%22)&group_by=developer&summarize=age_average:mean(age),counts:n()

spring:
  data:
    mongodb:
      uri: mongodb+srv://hiranjanperera7532:xxBcZHIuBBZhoAwL@iit-cluster.ea0cis1.mongodb.net/Dev-IQ-Tracker
